# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Introduction To Modern Rendering 
email: 
description: >- # this means to ignore newlines until "baseurl:"
 This course teaches the fundamentals of real-time rendering, covering rasterization,
 ray tracing, physically based rendering, and GPU architecture.
 You'll learn essential math, lighting techniques, and performance considerations
 while building a simple rendering engine. Designed for programmers interested in graphics,
 it provides a solid foundation for modern rendering techniques without focusing
 on specific graphics APIs.
baseurl: "/Modern-Rendering-Introduction" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alelievr
github_username:  alelievr/Modern-Rendering-Introduction

# Build settings
remote_theme: alelievr/jekyll-gitbook
plugins:
  - jekyll-feed

domain: modern-rendering.github.io
url: https://modern-rendering.github.io

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Theme config:
syntax_highlighter_style: monokai

toc:
    enabled: true
    h_min: 1
    h_max: 3

collections:
  articles:
    output: true
    permalink: /:path/
    sort_by: order

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: post

exclude:
  - _drafts

# Categories configuration
categories_order:
  - name: "Fundamentals"
    id: Fundamentals
  - name: "Math for 3D"
    id: Math3D
  - name: "Authoring"
    id: Authoring
  - name: "Render Pipeline"
    id: RenderPipeline 
  - name: "Materials"
    id: Materials
  - name: "Lighting"
    id: Lighting
  - name: "Transparency"
    id: Transparency
  - name: "Colors"
    id: Colors
  - name: "Optimization Techniques"
    id: OptimizationTechniques
  - name: "Miscellaneous"
    id: Miscellaneous

# Add footer configuration
footer:
  copyright: ""
  links:
  allow_override: true

favicon_path: assets/favicon.ico
